#Bringing all executables to shapes folder
all: a b c 
#Open xxSquare01.c
a: xxSquare01.c
    gcc -o xxSquare01.c xxSquare01.exe
    ../bin/xxSquare01.exe

#Open xxSquare02.c
b: xxSquare01.c
    gcc -o xxSquare02.c xxSquare02.exe
    ../bin/xxSquare02.exe

#Open xxSquare03.c
c: xxSquare03.c
    gcc -o xxSquare03.c xxSquare03.exe
    ../bin/xxSquare03.exe