#Bringing all executables to bin folder  
all: 01 02 03 04 05 06 07 08 09 10 11 12 13 

# Removing all executables from bin folder
clean: rm ../bin/*.exe

# Original Hello c file executable instructions and run
01: 01Hello.c
	gcc -o ../bin/01Hello.exe 01Hello.c
	../bin/01Hello.exe

# Command line arguments c file executable instructions and run
02: xxCLA01.c
	gcc -o ../bin/xxCLA01.exe xxCLA01.c
	../bin/xxCLA01.exe

# CLA file that prints out the name of the file and run
03: xxCLA02.c
	gcc -o ../bin/xxCLA02.exe xxCLA02.c
	../bin/xxCLA02.exe

# CLA file that also prints arguments and run
04: xxCLA03.c
	gcc -o ../bin/xxCLA03.exe xxCLA03.c
	../bin/xxCLA03.exe

# CLA file that includes sum of arguments and run
05: xxCLA04.c
	gcc -o ../bin/xxCLA04.exe xxCLA04.c
	../bin/xxCLA04.exe

# CLA file with min, max, and average of arguments and run
06: xxCLA05.c
	gcc -o ../bin/xxCLA05.exe xxCLA05.c
	../bin/xxCLA05.exe

# ASCII file executable instructions and run
07: xxASCII.c
	gcc -o ../bin/xxASCII.exe xxASCII.c
	../bin/xxASCII.exe

# Instructions for the bases file executable and run
08: xxBases.c
	gcc -o ../bin/xxBases.exe xxBases.c
	../bin/xxBases.exe

# Data types C file executable instructions and run
09: xxDataTypes01.c
	gcc -o ../bin/xxDataTypes01.exe xxDataTypes01.c
	../bin/xxDataTypes01.exe

# Argument conversions C file executable instructions and run
10: xxProduct.c
	gcc -o ../bin/xxProduct.exe xxProduct.c
	../bin/xxProduct.exe

# Compile 01Hello.c and run
11: 01Hello.c
	gcc -o ../bin/01Hello.exe 01Hello.c
	../bin/01Hello.exe

# Open and run Practice1.c
12: Practice1.c
	gcc -o Practice1.exe Practice1.c
	./Practice1.exe

# Open and run HelloWorld.c
13: HelloWorld.c
	gcc -o ../bin/HelloWorld.exe HelloWorld.c
	../bin/HelloWorld.exe

#Open and run StraightLine.c
14: StraightLine.c
	gcc -o ../bin/StraightLine.exe StraightLine.c
	../bin/StraightLine.exe

#Open and run Curve.c
15: StraightLine.c
	gcc -o ../bin/Curve.exe Curve.c
	../bin/Curve.exe

#Open and run Circle.c
16: Circle.c
	gcc -o ../bin/Circle.exe Circle.c
	../bin/Circle.exe

#Open and run Function.c
17: Function.c
	gcc -o ../bin/Function.exe Function.c
	../bin/Function.exe

#Open and run Arrays.c
18: Arrays.c
	gcc -o ../bin/Arrays.exe Arrays.c
	../bin/Arrays.exe

#Open and run MatrixManipulation.c
19: MatrixManipulation.c
	gcc -o ../bin/MatrixManipulation.exe MatrixManipulation.c
	../bin/MatrixManipulation.exe

#Open and run Transpose.c
20: Transpose.c
	gcc -o ../bin/Transpose.exe Transpose.c
	../bin/Transpose.exe

#Open and run Inverse.c
21: Inverse.c
	gcc -o ../bin/Inverse.exe Inverse.c
	../bin/Inverse.exe