#Bringing all executables to bin folder 
all: 01 02 03 04 05 07 08 09 10

#removing all executables from bin folder 
clean: rm ../bin/*.exe

#Original Hello C file executable instructions
01: 01Hello.c
gcc -o ../bin/01Hello.exe 01Hello.c

#Command line arguments C file executable instructions
02: xxCLA01.exe xxCLA01.c

#CLA file that prints out name of file 
03: xxCLA2.exe xxCLA02.c

#CLA file that also prints arguments
04: xxCLA03.c
gcc -o ../bin/xxCLA3.exe xxCLA3.c

#CLA file that includes sum of arguments
05: xxCLA04.c
gcc -o ../bin/xxCLA04.exe xxCLA04.c

#CLA file with min,max and average of arguments 
06: xxCLA05.c
gcc -o ../bin/xxCLA05.exe xxCLA05.c

#ASCII file executable instructions
07: xxASCII.C
    gcc -o ../bin/xxASCII.exe xxASCII.c

#Instructions for the bases file executable 
08: xxBases.C
gcc -o ../bin/xxBases.exe xxBases.c

#Data types c file executable instructions
09: xxDataTypes01.C
gcc -o ../bin/DataTypes01.exe xxDataTypes01.c

#Argument conversions c file executable instructions
10: xxProduct.c
gcc -o ../bin/xxProduct.exe xxProduct.c

#01Hello.c Launch
11: 01Hello.c
./../bin/01Hello.exe

#Compile 01Hello.c
12: 01Hello.c
    gcc -o 01Hello.exe 01Hello.c

13: Practice1.c
    gcc -o Practice1.c Practice1.exe