# Compile code with C++17 features and rules
all:
	g++ -std=c++17 harness.cpp scheduler.cpp -o harness.exe

# Run the program after building
run:
	./harness.exe

# Clean up the executable
clean:
	@if exist harness.exe del harness.exe
